globalnginx:
  hostname: globalnginx
  image: nginx
  volumes:
    - "/tmp/nginx:/etc/nginx/conf.d"
    - "~/units/globalnginx/certs:/etc/nginx/certs"
  expose:
    - "80"
    - "443"
  ports:
    - "80:80"
    - "443:443"

dockergen:
  hostname: dockergen
  image: jwilder/docker-gen
  volumes_from:
    - globalnginx
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    - "~/units/dockergen/:/etc/docker-gen/templates"
    
### The next line must be changed if moving this to a new folder. Change the part before _globalnginx_1 -watch to the name of the folder.
  command: -notify-sighup dockerdrupal_globalnginx_1 -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  links:
    - globalnginx

localdevdrupal:
  hostname: localdevdrupal
  image: meosch/localdevdrupal
  expose:
    - "80"
    - "22"
    - "3306"
  ports: 
#    - "9080:80"
    - "9022:22"
    - "9006:3306"
    - "9001:9001"
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
    - VIRTUAL_HOST=localdev.docker
  volumes:
    - "./public_html/:/var/www"
# PHP configuration overrides
    - "./.drude/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
  links:
    - dockergen

# CLI node
# Used for all console commands and tools.
cli:
  hostname: cli
  image: blinkreaction/drupal-cli:php-5.6
  volumes:
    # Project root folder mapping
#    - ./:/var/www
#    - ./project
    # PHP configuration overrides
    - "./.drude/etc/php5/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"
    # Host SSH keys mappings.
    # We try to map both options. The startup.sh script in cli container will decide which one to use.
    - /.ssh:/.ssh-b2d  # boot2docker-vagrant
    - ~/.ssh:/.ssh   # Linux
    # Acquia credentials mapping
    - /.acquia:/root/.acquia # boot2docker-vagrant
    #- ~/.acquia:/root/.acquia # Linux
  links:
#    - db
    - localdevdrupal
#    - web2
    - dockergen
#    - adminer
